# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29dd6b11bc4c17302bc6dc659d5813dd9dc129ab309f771fef449e94e7f619a5cd1e8e339dc2519ae7eebb08472623d857d4e092e02401c588a8eb047fbe48e0

test:
  secret_key_base: 50c3a57959599cb37da2b4d5fcb054f791ed4aa2748c2de2fe830437a32e730dda19b88c9d6113f176c3f0f54a1193944980806e5bbac951ae3b55a71d9a2b0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
